server_hostname: "your-ciphertrust-manager-host"
client_profile_default: "id-of-the-client-profile"
cte_client_profile_default: "name-of-cte-client-profile"
lifetime: "1d"
max_clients: 1
name_prefix: "ansible_token"
enable_ldt: 1
host_desc_default: "Client Installed with Ansible"
